version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.12"

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "shellcheck"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
